name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - 'streamsrv/**'
  pull_request:
    paths:
      - 'streamsrv/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Format check
        run: cargo fmt --all -- --check
        working-directory: streamsrv
      - name: Build release
        run: cargo build --release --verbose
        working-directory: streamsrv
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: streamsrv
          path: streamsrv/target/release/streamsrv
